/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vpnRegistrySol from "./VPNRegistry.sol";
export type { vpnRegistrySol };
export type { VPNSubscription } from "./VPNSubscription";
