services:
  # Backend Service (Define this first)
  - type: web
    name: vpn-backend
    runtime: node
    plan: free
    nodeVersion: 16.20.0
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

  # Frontend Service
  - type: web
    name: vpn-frontend
    runtime: node
    plan: free
    nodeVersion: 16.20.0
    buildCommand: cd frontend && npm install --legacy-peer-deps && CI=false npm run build
    startCommand: npx serve -s frontend/build
    envVars:
      - key: REACT_APP_API_URL
        value: "https://vpn-backend-yolj.onrender.com" 