services:
  # Backend Service (Define this first)
  - type: web
    name: vpn-backend
    runtime: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

  # Frontend Service
  - type: web
    name: vpn-frontend
    runtime: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          name: vpn-backend
          type: web
          property: url
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 