/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IVPNSubscription } from "./IVPNSubscription";
export type { VPNRegistry } from "./VPNRegistry";
