/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IVPNSubscription__factory } from "./IVPNSubscription__factory";
export { VPNRegistry__factory } from "./VPNRegistry__factory";
