/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVPNSubscription,
  IVPNSubscriptionInterface,
} from "../../../contracts/VPNRegistry.sol/IVPNSubscription";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "isSubscriptionActive",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVPNSubscription__factory {
  static readonly abi = _abi;
  static createInterface(): IVPNSubscriptionInterface {
    return new Interface(_abi) as IVPNSubscriptionInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IVPNSubscription {
    return new Contract(address, _abi, runner) as unknown as IVPNSubscription;
  }
}
