/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as vpnRegistrySol from "./VPNRegistry.sol";
export { VPNSubscription__factory } from "./VPNSubscription__factory";
